# Generated by Django 5.1.5 on 2025-01-25 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OADepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='部门名称')),
                ('intro', models.CharField(max_length=200, verbose_name='部门介绍')),
                ('leader', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_department', related_query_name='leader_department', to=settings.AUTH_USER_MODEL, verbose_name='部门经理')),
                ('manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_departments', related_query_name='manager_departments', to=settings.AUTH_USER_MODEL, verbose_name='部门领导')),
            ],
        ),
        migrations.AddField(
            model_name='oauser',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', related_query_name='staffs', to='oaauth.oadepartment', verbose_name='所属部门'),
        ),
    ]
