# Generated by Django 5.1.5 on 2025-02-04 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaauth', '0002_oadepartment_oauser_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauser',
            name='status',
            field=models.IntegerField(choices=[(1, 'Actived'), (2, 'Unactive'), (3, 'Locked')], default=2, verbose_name='用户状态'),
        ),
    ]
