# Generated by Django 5.1.5 on 2025-02-05 14:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='请假类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Absent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='请假标题')),
                ('request_content', models.TextField(verbose_name='请假内容')),
                ('status', models.IntegerField(choices=[(1, 'Auditing'), (2, 'Pass'), (3, 'Reject')], default=1, verbose_name='审核状态')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='请假发起时间')),
                ('response_content', models.TextField(verbose_name='审批意见')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_absents', related_query_name='my_absents', to=settings.AUTH_USER_MODEL, verbose_name='请假人')),
                ('responder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_absents', related_query_name='sub_absents', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('absent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absents', related_query_name='absents', to='absent.absenttype', verbose_name='请假类型')),
            ],
        ),
    ]
